name: xpneus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_auth: ^6.5.7
  google_sign_in: ^7.2.0
  firebase_core: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # 1. ADICIONE ESTA LINHA NAS DEPENDÊNCIAS DE DESENVOLVIMENTO
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/xpneus.png
    - assets/icone.png # Registre o arquivo do ícone aqui também

# 2. ADICIONE ESTE BLOCO COMPLETO NO FINAL DO ARQUIVO (Sem nenhum espaço antes)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icone.png"
  min_sdk_android: 21

  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.0

