// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrc1Iq119SzARkrI4447znNsCRXTkrjs',
    appId: '1:685505535233:web:28049e6b0758805624cf00',
    messagingSenderId: '685505535233',
    projectId: 'xpneus-estoque',
    authDomain: 'xpneus-estoque.firebaseapp.com',
    storageBucket: 'xpneus-estoque.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTE6M12A6eZFNTJ_LllCPaiS6aM_RlLw',
    appId: '1:685505535233:android:a3c21fc3b3ed1d4024cf00',
    messagingSenderId: '685505535233',
    projectId: 'xpneus-estoque',
    storageBucket: 'xpneus-estoque.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYIZmJqf8_NGZUvDMzt4Tfv1IUky9kfo',
    appId: '1:685505535233:ios:d45d03313858339c24cf00',
    messagingSenderId: '685505535233',
    projectId: 'xpneus-estoque',
    storageBucket: 'xpneus-estoque.firebasestorage.app',
    iosClientId: '685505535233-5ej3uq6fr24tbmv5tj23dsoqr5l665v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpneus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYIZmJqf8_NGZUvDMzt4Tfv1IUky9kfo',
    appId: '1:685505535233:ios:d45d03313858339c24cf00',
    messagingSenderId: '685505535233',
    projectId: 'xpneus-estoque',
    storageBucket: 'xpneus-estoque.firebasestorage.app',
    iosClientId: '685505535233-5ej3uq6fr24tbmv5tj23dsoqr5l665v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpneus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXrc1Iq119SzARkrI4447znNsCRXTkrjs',
    appId: '1:685505535233:web:cb990bfd0053e86424cf00',
    messagingSenderId: '685505535233',
    projectId: 'xpneus-estoque',
    authDomain: 'xpneus-estoque.firebaseapp.com',
    storageBucket: 'xpneus-estoque.firebasestorage.app',
  );
}
